services:
  server:
    build: ./server
  front:
    build:
      context: ./
      dockerfile: ./front/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
#   mongo:
#     image: mongo:latest
#     ports:
#       - "27017:27017"
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: 
#     volumes:
#       - mongo-data:/data/db
#   mongo-express:
#     image: mongo-express:latest
#     ports:
#       - "8081:8081"
#     depends_on:
#       - mongo
#     environment:
#       ME_CONFIG_MONGODB_SERVER: mongo
#       ME_CONFIG_MONGODB_ADMINUSERNAME: root
#       ME_CONFIG_MONGODB_ADMINPASSWORD: 
#       ME_CONFIG_BASICAUTH: "false"
# volumes:
#   mongo-data:
