version: "3"

tasks:
  front:
    cmds:
      - npm run dev
    dir: front
  server:
    cmds:
      - npm run dev
    dir: server
  default:
    deps:
      - front
      - server
  install-front:
    cmds:
      - npm install
    dir: front
  install-server:
    cmds:
      - npm install
    dir: server
  install:
    deps:
      - install-front
      - install-server
