version: "3"

tasks:
  front:
    cmds:
      - npm run dev
    dir: front
  server:
    cmds:
      - denon run -A ./src/main.ts
    dir: server
  default:
    deps:
      - front
      - server
  install:
    cmds:
      - npm install
    dir: front
      - npm install
    dir: server
